#!/bin/sh
echo "ShowStatus=yes" >> /etc/systemd/system.conf

echo I: Disable default link rule.
rm /lib/systemd/network/99-default.link
touch /lib/systemd/network/99-default.link
rm /lib/udev/rules.d/65-vyatta-net.rules
touch /lib/udev/rules.d/65-vyatta-net.rules

echo I: Update initramfs.
update-initramfs -u
